#include "Parse.h"

#include "Casting.h"
#include "Diagnostics.h"
#include "IdPool.h"
#include "Lex.h"

#include <array>
#include <cassert>
#include <codecvt>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <iterator>
#include <locale>
#include <memory>
#include <optional>
#include <regex>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

using namespace Lex;

namespace {

// Source range covering a single token [Start, End).
llvm::SMRange tokRange(const SourceStream &S, const Tok &T) {
  return {S.getLoc(T.Start), S.getLoc(T.End + 1)};
}

// Source range from a node's first-token offset to the current parse position.
llvm::SMRange rangeFrom(const SourceStream &S, size_t NodeStart) {
  return {S.getLoc(NodeStart), S.getLoc(S.getPosition())};
}

// Report a parse error anchored at a byte offset, if diagnostics are enabled.
void parseError(SourceStream &S, size_t Offset, const llvm::Twine &Msg) {
  if (auto *Diag = S.getDiagnostics()) {
    Diag->error(S.getLoc(Offset), Msg);
  }
}

// True once a diagnostic has been emitted, so backtracking can stop trying
// alternatives instead of cascading further errors.
bool hadError(const SourceStream &S) {
  auto *Diag = S.getDiagnostics();
  return Diag != nullptr && Diag->hadError();
}

} // namespace

// This is the main parse file that parses linklets generated by Racket
// Racket docs do not have a formal grammar in one place and it's indeed split
// into different pages. I have tried to collect all the relevant information
// here.
//
// Linklet grammar starts in
// https://docs.racket-lang.org/reference/linklets.html#%28tech._linklet%29
// but then you're forward to
// https://docs.racket-lang.org/reference/syntax-model.html#%28part._fully-expanded%29
// and this one still misses some important information, like the definition of
// datum for example.
//
// The following text will try to summarize what I understand from the docs, and
// as a reference for what I have implemented.
//
// Linklet grammar:
//
// linklet := (linklet [[<imported-id/renamed-id> ...] ...]
//                     [<exported-id/renamed> ...]
//               <defn-or-expr> ...)
//
// imported-id/renamed := <imported-id>
//                      | (<external-imported-id> <internal-imported-id>)
//
// exported-id/renamed := <exported-id>
//                      | (<internal-exported-id> <external-exported-id>)
//
// defn-or-expr := <defn> | <expr>                          - parseDefnOrExpr
//
// defn := (define-values (<id> ...) <expr>)                - parseDefineValues
//       | (define-syntaxes (<id> ...) <expr>)
//
// expr := <id>                                             - parseIdentifier
//       | (lambda <formals> <expr>)                        - parseLambda
//       | (case-lambda (<formals> <expr>) ...)
//       | (if <expr> <expr> <expr>)                        - parseIfCond
//       | (begin <expr> ...+)                              - parseBegin
//       | (begin0 <expr> ...+)                             - parseBegin
//       | (let-values ([<id> ...) <expr>] ...) <expr>)     - parseLetValues
//       | (letrec-values ([(<id> ...) <expr>] ...) <expr>)
//       | (set! <id> <expr>)                               - parseSetBang
//       | (quote <datum>)                                  - parseQuote
//       | (with-continuation-mark <expr> <expr> <expr>)
//       | (<expr> ...+)                                    - parseApplication
//       | (%variable-reference <id>)
//       | (%variable-reference (%top . id))  <- Allowed?
//       | (%variable-reference)              <- Allowed?
//
// formals := <id>                                          - parseFormals
//          | (<id> ...+ . id)
//          | (id ...)
//
// <id> := TODO
//
// <datum> := <self-quoting-datum> | <character> | TODO
//
// <character> := TODO
//
// <self-quoting-datum> := <boolean> | <number> | <string> | <byte-string>
//
// <boolean> := #t | #f
//
// <number> := <integer> | TODO
//
// <string> := TODO
//
// <byte-string> := TODO
//
// The following is a list of parsed runtime library functions that are not part
// of the core grammar:
// - values

std::vector<ast::Linklet::idpair_t> parseLinkletExports(SourceStream &S) {
  // parse a sequence of
  // (internal-exported-id external-exported-id)
  std::vector<ast::Linklet::idpair_t> Vec;

  while (true) {
    Tok T = gettok(S);
    if (!T.is(Tok::TokType::LPAREN)) {
      S.rewind(T.size());
      return Vec;
    }

    // parse internal-exported-id
    std::optional<Tok> T1 = maybeLexIdOrNumber(S);
    if (!T1) {
      return {};
    }

    // parse external-exported-id
    std::optional<Tok> T2 = maybeLexIdOrNumber(S);
    if (!T2) {
      return {};
    }

    T = gettok(S);
    if (!T.is(Tok::TokType::RPAREN)) {
      return {};
    }

    IdPool &IP = IdPool::instance();

    Vec.push_back(std::make_pair(IP.create(T1.value().Value),
                                 IP.create(T2.value().Value)));
  }

  return Vec;
}

std::unique_ptr<ast::TLNode> Parse::parseDefn(SourceStream &S) {
  auto DefnValues = parseDefineValues(S);
  if (!DefnValues) {
    return nullptr;
  }

  return DefnValues;
}

std::unique_ptr<ast::TLNode> Parse::parseDefnOrExpr(SourceStream &S) {
  if (hadError(S)) {
    return nullptr;
  }
  std::unique_ptr<ast::TLNode> D = parseDefn(S);
  if (D) {
    return D;
  }
  std::unique_ptr<ast::ExprNode> E = parseExpr(S);
  return dyn_castU<ast::TLNode>(E);
}

std::unique_ptr<ast::Integer> Parse::parseInteger(SourceStream &S) {
  std::optional<Tok> Num = gettok(S);
  if (!Num->is(Tok::TokType::NUM)) {
    S.rewind(Num->size());
    return nullptr;
  }

  // We know the wstring is mostly just digits with possibly a prefix minus
  // so convert to string.
  std::string_view V = Num.value().Value;
  std::string NumStr(V.cbegin(), V.cend());

  auto I = std::make_unique<ast::Integer>(NumStr);
  I->setRange(tokRange(S, *Num));
  return I;
}

// An expression is either:
// - an integer
// - an identifier
// - a values
// - an arithmetic plus
// - a lambda
// - a begin
std::unique_ptr<ast::ExprNode> Parse::parseExpr(SourceStream &S) {
  // Once a diagnostic has been emitted, stop trying alternatives so a single
  // error unwinds cleanly instead of cascading.
  if (hadError(S)) {
    return nullptr;
  }

  std::unique_ptr<ast::Integer> I = parseInteger(S);
  if (I) {
    return I;
  }

  std::unique_ptr<ast::BooleanLiteral> Bool = parseBooleanLiteral(S);
  if (Bool) {
    return Bool;
  }

  // If the expression is quoted, then identifier is a symbol.
  std::unique_ptr<ast::Identifier> Id = parseIdentifier(S);
  if (Id) {
    return Id;
  }

  std::unique_ptr<ast::Values> V = parseValues(S);
  if (V) {
    return V;
  }

  std::unique_ptr<ast::Lambda> L = parseLambda(S);
  if (L) {
    return L;
  }

  std::unique_ptr<ast::Begin> B = parseBegin(S);
  if (B) {
    return B;
  }

  std::unique_ptr<ast::SetBang> SB = parseSetBang(S);
  if (SB) {
    return SB;
  }

  std::unique_ptr<ast::IfCond> IC = parseIfCond(S);
  if (IC) {
    return IC;
  }

  std::unique_ptr<ast::LetValues> LV = parseLetValues(S);
  if (LV) {
    return LV;
  }

  // quote must be tried before application so that (quote datum) is not
  // greedily consumed as a plain application of `quote`.
  std::unique_ptr<ast::QuotedExpr> Q = parseQuote(S);
  if (Q) {
    return Q;
  }

  std::unique_ptr<ast::Application> A = parseApplication(S);
  if (A) {
    return A;
  }

  return nullptr;
}

// Parse a quoted datum (self-quoting value). Inside quoted data every compound
// form is just a list and identifiers (even keywords) are symbols; special
// forms such as lambda/values are NOT recognised here.
std::unique_ptr<ast::ValueNode> Parse::parseValue(SourceStream &S) {
  if (hadError(S)) {
    return nullptr;
  }
  if (auto I = parseInteger(S)) {
    return I;
  }
  if (auto Bool = parseBooleanLiteral(S)) {
    return Bool;
  }
  if (auto C = parseChar(S)) {
    return C;
  }
  if (auto Str = parseString(S)) {
    return Str;
  }
  if (auto Vec = parseVector(S)) {
    return Vec;
  }
  // 'x and (quote x) nested inside data read as a (quoted) datum.
  if (auto Q = parseQuote(S)) {
    return Q;
  }
  if (auto Sym = parseSymbol(S)) {
    return Sym;
  }
  if (auto L = parseLiteralList(S)) {
    return L;
  }
  return nullptr;
}

std::unique_ptr<ast::Identifier> Parse::parseIdentifier(SourceStream &S) {
  Tok IDTok = gettok(S);
  if (!IDTok.is(Tok::TokType::ID)) {
    S.rewind(IDTok.size());
    return nullptr;
  }
  auto Id =
      std::make_unique<ast::Identifier>(IdPool::instance().create(IDTok.Value));
  Id->setRange(tokRange(S, IDTok));

  return Id;
}

// Inside quoted data an identifier is a symbol. The lexer eagerly turns known
// keywords (lambda, quote, define-values, ...) into dedicated tokens, but as
// data they are ordinary symbols, so accept them here too.
static bool isSymbolTok(const Tok &T) {
  return T.is(Tok::TokType::ID) || T.is(Tok::TokType::LAMBDA) ||
         T.is(Tok::TokType::QUOTE) || T.is(Tok::TokType::DEFINE_VALUES) ||
         T.is(Tok::TokType::VALUES) || T.is(Tok::TokType::LINKLET) ||
         T.is(Tok::TokType::LETREC_VALUES) || T.is(Tok::TokType::BEGIN) ||
         T.is(Tok::TokType::BEGIN0) || T.is(Tok::TokType::CASE_LAMBDA) ||
         T.is(Tok::TokType::IF) || T.is(Tok::TokType::VOID) ||
         T.is(Tok::TokType::LET_VALUES) || T.is(Tok::TokType::SETBANG) ||
         T.is(Tok::TokType::WITH_CONTINUATION_MARK) ||
         T.is(Tok::TokType::K_VARIABLE_REFERENCE) ||
         T.is(Tok::TokType::RAISE_ARGUMENT_ERROR) ||
         T.is(Tok::TokType::PROCEDURE_ARITY_INCLUDES_C) ||
         T.is(Tok::TokType::MAKE_STRUCT_TYPE);
}

// Decode a CHAR_HEX lexeme (a u/x/U/X prefix followed by hex digits, e.g.
// "u03bb") into the UTF-8 bytes of the represented code point, so the character
// prints as its glyph (#\λ) rather than the escape.
// UTF-8 encode a single code point onto Out.
static void appendUTF8(unsigned CP, std::string &Out) {
  if (CP < 0x80) {
    Out.push_back(static_cast<char>(CP));
  } else if (CP < 0x800) {
    Out.push_back(static_cast<char>(0xC0 | (CP >> 6)));
    Out.push_back(static_cast<char>(0x80 | (CP & 0x3F)));
  } else if (CP < 0x10000) {
    Out.push_back(static_cast<char>(0xE0 | (CP >> 12)));
    Out.push_back(static_cast<char>(0x80 | ((CP >> 6) & 0x3F)));
    Out.push_back(static_cast<char>(0x80 | (CP & 0x3F)));
  } else {
    Out.push_back(static_cast<char>(0xF0 | (CP >> 18)));
    Out.push_back(static_cast<char>(0x80 | ((CP >> 12) & 0x3F)));
    Out.push_back(static_cast<char>(0x80 | ((CP >> 6) & 0x3F)));
    Out.push_back(static_cast<char>(0x80 | (CP & 0x3F)));
  }
}

// Printed spelling (the text after #\) for a code point, in Racket's `print`
// form: named control characters use their name, other non-graphic ASCII
// controls use the #\uHHHH escape (uppercase), everything else its UTF-8 glyph.
static std::string charReprFromCodePoint(unsigned CP) {
  switch (CP) {
  case 0x00:
    return "nul";
  case 0x08:
    return "backspace";
  case 0x09:
    return "tab";
  case 0x0A:
    return "newline";
  case 0x0B:
    return "vtab";
  case 0x0C:
    return "page";
  case 0x0D:
    return "return";
  case 0x20:
    return "space";
  case 0x7F:
    return "rubout";
  default:
    break;
  }
  if (CP < 0x20) {
    char Buf[8];
    std::snprintf(Buf, sizeof(Buf), "u%04X", CP);
    return std::string(Buf);
  }
  std::string Out;
  appendUTF8(CP, Out);
  return Out;
}

// Decode a CHAR_HEX lexeme (a u/x/U/X prefix followed by hex digits, e.g.
// "u03bb") to its Racket printed spelling, so the escape for U+0020 prints as
// #\space and the escape for U+03BB as its glyph.
static std::string decodeHexChar(std::string_view HexTok) {
  auto HexVal = [](char C) -> unsigned {
    if (C >= '0' && C <= '9')
      return C - '0';
    if (C >= 'a' && C <= 'f')
      return C - 'a' + 10;
    return C - 'A' + 10;
  };
  unsigned CodePoint = 0;
  for (char C : HexTok.substr(1)) // skip the u/x/U/X prefix
    CodePoint = CodePoint * 16 + HexVal(C);
  return charReprFromCodePoint(CodePoint);
}

// Parse a character datum. The lexer distinguishes plain characters (#\a),
// named characters (#\space) and hex-escaped characters (#\uHHHH); all three
// are Char value nodes. Named characters keep their name; hex escapes decode to
// the represented glyph.
std::unique_ptr<ast::Char> Parse::parseChar(SourceStream &S) {
  size_t Start = S.getPosition();
  Tok T = gettok(S);
  if (T.is(Tok::TokType::CHAR) || T.is(Tok::TokType::CHAR_NAMED)) {
    auto C = std::make_unique<ast::Char>(T.Value);
    C->setRange(tokRange(S, T));
    return C;
  }
  if (T.is(Tok::TokType::CHAR_HEX)) {
    auto C = std::make_unique<ast::Char>(decodeHexChar(T.Value));
    C->setRange(tokRange(S, T));
    return C;
  }
  S.rewindTo(Start);
  return nullptr;
}

// Parse a string datum ("z"). The lexer produces a STRING token whose value is
// the string's read lexeme (including the surrounding quotes).
std::unique_ptr<ast::String> Parse::parseString(SourceStream &S) {
  size_t Start = S.getPosition();
  Tok T = gettok(S);
  if (!T.is(Tok::TokType::STRING)) {
    S.rewindTo(Start);
    return nullptr;
  }
  auto Str = std::make_unique<ast::String>(T.Value);
  Str->setRange(tokRange(S, T));
  return Str;
}

std::unique_ptr<ast::Symbol> Parse::parseSymbol(SourceStream &S) {
  Tok T = gettok(S);
  if (!isSymbolTok(T)) {
    S.rewind(T.size());
    return nullptr;
  }
  auto Sym = std::make_unique<ast::Symbol>(T.Value);
  Sym->setRange(tokRange(S, T));
  return Sym;
}

// Parses an expression of the form:
// (define-values (id ...) expr)
std::unique_ptr<ast::DefineValues> Parse::parseDefineValues(SourceStream &S) {
  size_t Start = S.getPosition();

  Tok T = gettok(S);
  if (!T.is(Tok::TokType::LPAREN)) {
    S.rewindTo(Start);
    return nullptr;
  }

  const size_t NodeStart = T.Start;

  Tok DVTok = gettok(S);
  if (!DVTok.is(Tok::TokType::DEFINE_VALUES)) {
    S.rewindTo(Start);
    return nullptr;
  }

  // parse the list of ids
  llvm::SmallVector<ast::Identifier> Ids;
  T = gettok(S);
  if (!T.is(Tok::TokType::LPAREN)) {
    parseError(S, S.getPosition(),
               "expected '(' to open identifier list in 'define-values'");
    return nullptr;
  }

  while (true) {
    std::unique_ptr<ast::Identifier> Id = parseIdentifier(S);
    if (!Id) {
      break;
    }
    Ids.emplace_back(*Id);
  }

  T = gettok(S);
  if (!T.is(Tok::TokType::RPAREN)) {
    parseError(S, S.getPosition(),
               "expected ')' after identifier list in 'define-values'");
    return nullptr;
  }

  // parse the expression
  std::unique_ptr<ast::ExprNode> Expr = parseExpr(S);
  if (!Expr) {
    if (!hadError(S)) {
      parseError(S, S.getPosition(),
                 "expected value expression in 'define-values'");
    }
    return nullptr;
  }

  T = gettok(S);
  if (!T.is(Tok::TokType::RPAREN)) {
    if (!hadError(S)) {
      parseError(S, S.getPosition(), "expected ')' to close 'define-values'");
    }
    return nullptr;
  }

  auto DV = std::make_unique<ast::DefineValues>(Ids, Expr);
  DV->setRange(rangeFrom(S, NodeStart));
  return DV;
}

// Parses an expression of the form:
// (values expr ...)
std::unique_ptr<ast::Values> Parse::parseValues(SourceStream &S) {
  size_t Start = S.getPosition();

  Tok T = gettok(S);
  if (!T.is(Tok::TokType::LPAREN)) {
    S.rewindTo(Start);
    return nullptr;
  }

  const size_t NodeStart = T.Start;

  std::optional<Tok> IDTok = maybeLexIdOrNumber(S);
  if (!IDTok || !IDTok->is(Tok::TokType::VALUES)) {
    S.rewindTo(Start);
    return nullptr;
  }

  llvm::SmallVector<std::unique_ptr<ast::ExprNode>> Exprs;
  while (true) {
    std::unique_ptr<ast::ExprNode> Expr = parseExpr(S);
    if (!Expr) {
      break;
    }
    Exprs.push_back(std::move(Expr));
  }

  if (hadError(S)) {
    return nullptr;
  }

  T = gettok(S);
  if (!T.is(Tok::TokType::RPAREN)) {
    parseError(S, S.getPosition(), "expected ')' to close 'values'");
    return nullptr;
  }

  auto Vs = std::make_unique<ast::Values>(std::move(Exprs));
  Vs->setRange(rangeFrom(S, NodeStart));
  return Vs;
}

std::unique_ptr<ast::Linklet> Parse::parseLinklet(SourceStream &S) {
  //   (linklet [[imported-id/renamed ...] ...]
  //          [exported-id/renamed ...]
  //   defn-or-expr ...)
  //
  // imported-id/renamed	 	=	 	imported-id
  //  	 	|	 	(external-imported-id
  //  internal-imported-id)
  //
  // exported-id/renamed	 	=	 	exported-id
  //  	 	|	 	(internal-exported-id
  //  external-exported-id)

  auto Linklet = std::make_unique<ast::Linklet>();

  Tok T = gettok(S);
  if (!T.is(Tok::TokType::LPAREN)) {
    parseError(S, S.getPosition(), "expected '(' at start of linklet");
    return nullptr;
  }

  const size_t NodeStart = T.Start;

  T = gettok(S);
  if (!T.is(Tok::TokType::LINKLET)) {
    parseError(S, S.getPosition(), "expected 'linklet' keyword");
    return nullptr;
  }

  T = gettok(S);
  if (!T.is(Tok::TokType::LPAREN)) {
    parseError(S, S.getPosition(), "expected '(' to open linklet import list");
    return nullptr;
  }

  /// FIXME: Add imports support
  T = gettok(S);
  if (!T.is(Tok::TokType::RPAREN)) {
    parseError(S, S.getPosition(),
               "expected ')' to close linklet import list (imports are not yet "
               "supported)");
    return nullptr;
  }

  T = gettok(S);
  if (!T.is(Tok::TokType::LPAREN)) {
    parseError(S, S.getPosition(), "expected '(' to open linklet export list");
    return nullptr;
  }

  // Parsing linklet exports
  const std::vector<ast::Linklet::idpair_t> Exports = parseLinkletExports(S);
  for (const auto &E : Exports) {
    Linklet->appendExport(E.first, E.second);
  }

  T = gettok(S);
  if (!T.is(Tok::TokType::RPAREN)) {
    parseError(S, S.getPosition(), "expected ')' to close linklet export list");
    return nullptr;
  }

  while (true) {
    std::unique_ptr<ast::TLNode> Exp = parseDefnOrExpr(S);
    if (!Exp) {
      break;
    }
    Linklet->appendBodyForm(std::move(Exp));
  }

  if (hadError(S)) {
    return nullptr;
  }

  T = gettok(S);
  if (!T.is(Tok::TokType::RPAREN)) {
    parseError(S, S.getPosition(),
               "expected a definition, an expression, or ')' to close linklet");
    return nullptr;
  }

  if (Linklet->bodyFormsCount() == 0) {
    parseError(S, NodeStart,
               "linklet body must contain at least one definition or "
               "expression");
    return nullptr;
  }

  Linklet->setRange(rangeFrom(S, NodeStart));
  return Linklet;
}

// Parse lambda expression of the form:
// (lambda <formals> body)
// where formals are parsed by parseFormals
std::unique_ptr<ast::Lambda> Parse::parseLambda(SourceStream &S) {
  size_t Start = S.getPosition();

  Tok T = gettok(S);
  if (!T.is(Tok::TokType::LPAREN)) {
    S.rewindTo(Start);
    return nullptr;
  }

  const size_t NodeStart = T.Start;

  T = gettok(S);
  if (!T.is(Tok::TokType::LAMBDA)) {
    S.rewindTo(Start);
    return nullptr;
  }

  // Lets create the lambda node
  std::unique_ptr<ast::Lambda> Lambda = std::make_unique<ast::Lambda>();

  std::unique_ptr<ast::Formal> Formals = parseFormals(S);
  if (!Formals) {
    if (!hadError(S)) {
      parseError(S, S.getPosition(), "expected formals after 'lambda'");
    }
    return nullptr;
  }
  Lambda->setFormals(std::move(Formals));

  std::unique_ptr<ast::ExprNode> Body = parseExpr(S);
  if (!Body) {
    if (!hadError(S)) {
      parseError(S, S.getPosition(), "expected body expression in lambda");
    }
    return nullptr;
  }
  Lambda->setBody(std::move(Body));

  T = gettok(S);
  if (!T.is(Tok::TokType::RPAREN)) {
    if (!hadError(S)) {
      parseError(S, S.getPosition(), "expected ')' to close lambda");
    }
    return nullptr;
  }

  Lambda->setRange(rangeFrom(S, NodeStart));
  return Lambda;
}

// Parse formals of the form:
// (id ...)
// (id ... . id)
// id
std::unique_ptr<ast::Formal> Parse::parseFormals(SourceStream &S) {
  size_t Start = S.getPosition();

  Tok T = gettok(S);
  if (!T.is(Tok::TokType::LPAREN)) {
    S.rewindTo(Start);

    // If it's not a list, it's a single id
    std::unique_ptr<ast::Identifier> Id = parseIdentifier(S);
    if (Id) {
      return std::make_unique<ast::IdentifierFormal>(*Id);
    }

    S.rewindTo(Start);
    return nullptr;
  }

  llvm::SmallVector<ast::Identifier> Ids;
  while (true) {
    T = gettok(S);
    if (T.is(Tok::TokType::RPAREN) || T.is(Tok::TokType::DOT)) {
      break;
    }
    S.rewind(T.size()); // put the token back

    std::unique_ptr<ast::Identifier> Id = parseIdentifier(S);
    if (!Id) {
      S.rewindTo(Start);
      return nullptr;
    }

    Ids.push_back(*Id);
  }

  if (T.is(Tok::TokType::DOT)) {

    std::unique_ptr<ast::Identifier> RestId = parseIdentifier(S);
    if (!RestId) {
      S.rewindTo(Start);
      return nullptr;
    }

    T = gettok(S);
    if (!T.is(Tok::TokType::RPAREN)) {
      S.rewindTo(Start);
      return nullptr;
    }

    return std::make_unique<ast::ListRestFormal>(Ids, *RestId);
  }

  if (!T.is(Tok::TokType::RPAREN)) {
    S.rewindTo(Start);
    return nullptr;
  }

  return std::make_unique<ast::ListFormal>(Ids);
}

// Parse lambda expression of the form:
// (begin <expr>+) | (begin0 <expr>+)
std::unique_ptr<ast::Begin> Parse::parseBegin(SourceStream &S) {
  size_t Start = S.getPosition();

  Tok T = gettok(S);
  if (!T.is(Tok::TokType::LPAREN)) {
    S.rewindTo(Start);
    return nullptr;
  }

  const size_t NodeStart = T.Start;

  T = gettok(S);
  if (!T.is(Tok::TokType::BEGIN) && !T.is(Tok::TokType::BEGIN0)) {
    S.rewindTo(Start);
    return nullptr;
  }

  // Lets create the begin node
  std::unique_ptr<ast::Begin> Begin = std::make_unique<ast::Begin>();
  if (T.is(Tok::TokType::BEGIN0)) {
    Begin->markAsBegin0();
  }

  while (true) {
    std::unique_ptr<ast::ExprNode> Exp = parseExpr(S);
    if (!Exp) {
      break;
    }
    Begin->appendExpr(std::move(Exp));
  }

  if (hadError(S)) {
    return nullptr;
  }

  T = gettok(S);
  if (!T.is(Tok::TokType::RPAREN)) {
    parseError(S, S.getPosition(), "expected ')' to close 'begin'");
    return nullptr;
  }

  if (Begin->bodyCount() == 0) {
    parseError(S, NodeStart, "begin form requires at least one expression");
    return nullptr;
  }

  Begin->setRange(rangeFrom(S, NodeStart));
  return Begin;
}

// Parse application of the form:
// (<expr> <expr>*)
std::unique_ptr<ast::Application> Parse::parseApplication(SourceStream &S) {
  size_t Start = S.getPosition();

  Tok T = gettok(S);
  if (!T.is(Tok::TokType::LPAREN)) {
    S.rewindTo(Start);
    return nullptr;
  }

  const size_t NodeStart = T.Start;
  auto App = std::make_unique<ast::Application>();

  while (true) {
    std::unique_ptr<ast::ExprNode> Exp = parseExpr(S);
    if (!Exp) {
      break;
    }
    App->appendExpr(std::move(Exp));
  }

  T = gettok(S);
  if (!T.is(Tok::TokType::RPAREN)) {
    S.rewindTo(Start);
    return nullptr;
  }

  if (App->length() == 0) {
    S.rewindTo(Start);
    return nullptr;
  }

  App->setRange(rangeFrom(S, NodeStart));
  return App;
}

// Parse set!:
// (set! <id> <expr>)
std::unique_ptr<ast::SetBang> Parse::parseSetBang(SourceStream &S) {
  size_t Start = S.getPosition();

  Tok T = gettok(S);
  if (!T.is(Tok::TokType::LPAREN)) {
    S.rewindTo(Start);
    return nullptr;
  }

  const size_t NodeStart = T.Start;

  T = gettok(S);
  if (!T.is(Tok::TokType::SETBANG)) {
    S.rewindTo(Start);
    return nullptr;
  }

  auto Set = std::make_unique<ast::SetBang>();

  std::unique_ptr<ast::Identifier> Id = parseIdentifier(S);
  if (!Id) {
    if (!hadError(S)) {
      parseError(S, S.getPosition(), "expected identifier after 'set!'");
    }
    return nullptr;
  }
  Set->setIdentifier(std::move(Id));

  std::unique_ptr<ast::ExprNode> Exp = parseExpr(S);
  if (!Exp) {
    if (!hadError(S)) {
      parseError(S, S.getPosition(), "expected expression in 'set!'");
    }
    return nullptr;
  }
  Set->setExpr(std::move(Exp));

  T = gettok(S);
  if (!T.is(Tok::TokType::RPAREN)) {
    if (!hadError(S)) {
      parseError(S, S.getPosition(), "expected ')' to close 'set!'");
    }
    return nullptr;
  }

  Set->setRange(rangeFrom(S, NodeStart));
  return Set;
}

std::unique_ptr<ast::IfCond> Parse::parseIfCond(SourceStream &S) {
  size_t Start = S.getPosition();

  Tok T = gettok(S);
  if (!T.is(Tok::TokType::LPAREN)) {
    S.rewindTo(Start);
    return nullptr;
  }

  const size_t NodeStart = T.Start;

  T = gettok(S);
  if (!T.is(Tok::TokType::IF)) {
    S.rewindTo(Start);
    return nullptr;
  }

  auto If = std::make_unique<ast::IfCond>();

  std::unique_ptr<ast::ExprNode> Cond = parseExpr(S);
  if (!Cond) {
    if (!hadError(S)) {
      parseError(S, S.getPosition(), "expected condition expression in 'if'");
    }
    return nullptr;
  }
  If->setCond(std::move(Cond));

  std::unique_ptr<ast::ExprNode> Then = parseExpr(S);
  if (!Then) {
    if (!hadError(S)) {
      parseError(S, S.getPosition(), "expected then expression in 'if'");
    }
    return nullptr;
  }
  If->setThen(std::move(Then));

  std::unique_ptr<ast::ExprNode> Else = parseExpr(S);
  if (!Else) {
    if (!hadError(S)) {
      parseError(S, S.getPosition(), "expected else expression in 'if'");
    }
    return nullptr;
  }
  If->setElse(std::move(Else));

  T = gettok(S);
  if (!T.is(Tok::TokType::RPAREN)) {
    if (!hadError(S)) {
      parseError(S, S.getPosition(), "expected ')' to close 'if'");
    }
    return nullptr;
  }

  If->setRange(rangeFrom(S, NodeStart));
  return If;
}

// Parse boolean literal
std::unique_ptr<ast::BooleanLiteral>
Parse::parseBooleanLiteral(SourceStream &S) {
  size_t Start = S.getPosition();

  Tok T = gettok(S);
  if (T.is(Tok::TokType::BOOL_TRUE)) {
    auto B = std::make_unique<ast::BooleanLiteral>(true);
    B->setRange(tokRange(S, T));
    return B;
  }
  if (T.is(Tok::TokType::BOOL_FALSE)) {
    auto B = std::make_unique<ast::BooleanLiteral>(false);
    B->setRange(tokRange(S, T));
    return B;
  }
  S.rewindTo(Start);

  return nullptr;
}

// Parse a let-values form.
// (let-values ([(id ...) val-expr] ...) body ...+)
std::unique_ptr<ast::LetValues> Parse::parseLetValues(SourceStream &S) {
  size_t Start = S.getPosition();

  Tok T = gettok(S);
  if (!T.is(Tok::TokType::LPAREN)) {
    S.rewindTo(Start);
    return nullptr;
  }

  const size_t NodeStart = T.Start;

  T = gettok(S);
  if (!T.is(Tok::TokType::LET_VALUES)) {
    S.rewindTo(Start);
    return nullptr;
  }

  auto Let = std::make_unique<ast::LetValues>();

  T = gettok(S);
  if (!T.is(Tok::TokType::LPAREN)) {
    parseError(S, S.getPosition(),
               "expected '(' to open bindings in 'let-values'");
    return nullptr;
  }

  while (true) {
    T = gettok(S);
    if (T.is(Tok::TokType::RPAREN)) {
      break;
    }

    // Parse the binding.
    if (!T.is(Tok::TokType::LPAREN)) {
      parseError(S, S.getPosition(),
                 "expected '(' to open a binding in 'let-values'");
      return nullptr;
    }

    // Parse list of identifiers.
    T = gettok(S);
    if (!T.is(Tok::TokType::LPAREN)) {
      parseError(
          S, S.getPosition(),
          "expected '(' to open identifier list in 'let-values' binding");
      return nullptr;
    }

    llvm::SmallVector<ast::Identifier> Ids;
    while (true) {
      T = gettok(S);
      if (T.is(Tok::TokType::RPAREN)) {
        break;
      }

      S.rewind(T.size());
      std::unique_ptr<ast::Identifier> Id = parseIdentifier(S);
      if (!Id) {
        parseError(S, S.getPosition(),
                   "expected identifier in 'let-values' binding");
        return nullptr;
      }
      Ids.push_back(*Id);
    }

    // Parse the value expression.
    std::unique_ptr<ast::ExprNode> Val = parseExpr(S);
    if (!Val) {
      if (!hadError(S)) {
        parseError(S, S.getPosition(),
                   "expected value expression in 'let-values' binding");
      }
      return nullptr;
    }

    T = gettok(S);
    if (!T.is(Tok::TokType::RPAREN)) {
      if (!hadError(S)) {
        parseError(S, S.getPosition(),
                   "expected ')' to close 'let-values' binding");
      }
      return nullptr;
    }

    Let->appendBinding(std::move(Ids), std::move(Val));
  }

  while (true) {
    std::unique_ptr<ast::ExprNode> Exp = parseExpr(S);
    if (!Exp) {
      break;
    }
    Let->appendBody(std::move(Exp));
  }

  if (hadError(S)) {
    return nullptr;
  }

  T = gettok(S);
  if (!T.is(Tok::TokType::RPAREN)) {
    parseError(S, S.getPosition(), "expected ')' to close 'let-values'");
    return nullptr;
  }

  if (Let->bodyCount() == 0) {
    parseError(S, NodeStart,
               "let-values requires at least one body expression");
    return nullptr;
  }

  Let->setRange(rangeFrom(S, NodeStart));
  return Let;
}

// Parse a quoted form, in either surface syntax:
//   (quote datum)
//   'datum
// The datum is any self-quoting value (see parseValue). Characters, strings
// and vectors are not represented yet and will fail to parse.
std::unique_ptr<ast::QuotedExpr> Parse::parseQuote(SourceStream &S) {
  size_t Start = S.getPosition();

  Tok T = gettok(S);

  // (quote datum): the leading paren followed by the quote keyword.
  if (T.is(Tok::TokType::LPAREN)) {
    Tok Q = gettok(S);
    if (!Q.is(Tok::TokType::QUOTE)) {
      S.rewindTo(Start);
      return nullptr;
    }

    std::unique_ptr<ast::ValueNode> Datum = parseValue(S);
    if (!Datum) {
      if (!hadError(S)) {
        parseError(S, S.getPosition(), "expected datum after 'quote'");
      }
      return nullptr;
    }

    Tok RP = gettok(S);
    if (!RP.is(Tok::TokType::RPAREN)) {
      if (!hadError(S)) {
        parseError(S, S.getPosition(), "expected ')' to close 'quote'");
      }
      return nullptr;
    }

    auto QE = std::make_unique<ast::QuotedExpr>();
    QE->setQuotedExpr(std::move(Datum));
    QE->setRange(rangeFrom(S, T.Start));
    return QE;
  }

  // 'datum
  if (T.is(Tok::TokType::SYMBOLMARK)) {
    std::unique_ptr<ast::ValueNode> Datum = parseValue(S);
    if (!Datum) {
      if (!hadError(S)) {
        parseError(S, S.getPosition(), "expected datum after quote (')");
      }
      return nullptr;
    }

    auto QE = std::make_unique<ast::QuotedExpr>();
    QE->setQuotedExpr(std::move(Datum));
    QE->setRange(rangeFrom(S, T.Start));
    return QE;
  }

  S.rewindTo(Start);
  return nullptr;
}

// Parse a vector datum: #( datum ... ). The lexer produces a VECTOR_START token
// for the leading #(; elements are data parsed until the closing paren.
std::unique_ptr<ast::Vector> Parse::parseVector(SourceStream &S) {
  size_t Start = S.getPosition();

  Tok T = gettok(S);
  if (!T.is(Tok::TokType::VECTOR_START)) {
    S.rewindTo(Start);
    return nullptr;
  }

  const size_t NodeStart = T.Start;
  auto V = std::make_unique<ast::Vector>();

  while (true) {
    size_t Before = S.getPosition();
    T = gettok(S);
    if (T.is(Tok::TokType::RPAREN)) {
      break;
    }
    S.rewindTo(Before);

    std::unique_ptr<ast::ValueNode> Elem = parseValue(S);
    if (!Elem) {
      if (!hadError(S)) {
        parseError(S, S.getPosition(), "expected vector element or ')'");
      }
      return nullptr;
    }
    V->appendExpr(std::move(Elem));
  }

  V->setRange(rangeFrom(S, NodeStart));
  return V;
}

// Parse a literal (proper or dotted) list of data: ( datum ... )
// A dotted tail whose value is itself a list is spliced, so (1 2 . (3)) reads
// as (1 2 3). A dotted tail that is a non-list atom (a true improper list) is
// not represented yet.
std::unique_ptr<ast::List> Parse::parseLiteralList(SourceStream &S) {
  size_t Start = S.getPosition();

  Tok T = gettok(S);
  if (!T.is(Tok::TokType::LPAREN)) {
    S.rewindTo(Start);
    return nullptr;
  }

  const size_t NodeStart = T.Start;
  auto L = std::make_unique<ast::List>();

  while (true) {
    T = gettok(S);
    if (T.is(Tok::TokType::RPAREN)) {
      break;
    }

    if (T.is(Tok::TokType::DOT)) {
      std::unique_ptr<ast::ValueNode> Tail = parseValue(S);
      if (!Tail) {
        S.rewindTo(Start);
        return nullptr;
      }

      T = gettok(S);
      if (!T.is(Tok::TokType::RPAREN)) {
        S.rewindTo(Start);
        return nullptr;
      }

      if (auto *TailList = llvm::dyn_cast<ast::List>(Tail.get())) {
        // A list tail splices into this list: (1 2 . (3)) reads as (1 2 3).
        // If that tail is itself dotted, its improper tail carries over.
        for (auto const &V : TailList->values()) {
          L->appendExpr(std::unique_ptr<ast::ValueNode>(V->clone()));
        }
        if (TailList->hasTail()) {
          L->setTail(
              std::unique_ptr<ast::ValueNode>(TailList->getTail()->clone()));
        }
      } else {
        // A non-list tail makes this an improper (dotted) list: (1 2 . x).
        L->setTail(std::move(Tail));
      }
      break;
    }

    S.rewind(T.size());
    std::unique_ptr<ast::ValueNode> Exp = parseValue(S);
    if (!Exp) {
      S.rewindTo(Start);
      return nullptr;
    }
    L->appendExpr(std::move(Exp));
  }

  L->setRange(rangeFrom(S, NodeStart));
  return L;
}
