name: Scan-Build

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.cpp'
      - '**.td'
      - '**.h'
      - '**.inc'
      - '**.def'
      - '**.h.in'

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang-15 clang-tools-15 llvm-15-dev llvm-15-tools mlir-15-tools libmlir-15-dev git ninja-build python3-pip

      - name: Install FileCheck alternative
        run: | 
          sudo update-alternatives --install /usr/bin/FileCheck FileCheck /usr/bin/FileCheck-15 1
          sudo update-alternatives --install /usr/bin/scan-build scan-build /usr/bin/scan-build-15 1

      - name: Run scan-build
        run: |
          git fetch origin main
          git checkout main
          mkdir build
          cd build
          cmake -G "Unix Makefiles" -DCMAKE_PREFIX_PATH="/usr/lib/llvm-15/cmake;/usr/lib/llvm-15/lib/cmake/mlir/" -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_C_COMPILER=clang-15 -DCMAKE_CXX_COMPILER=clang++-15 ..
          scan-build -o ../base-analysis make
          cd ..
          rm -Rf build
          git checkout ${{ github.sha }}
          mkdir build
          cd build
          cmake -G "Unix Makefiles" -DCMAKE_PREFIX_PATH="/usr/lib/llvm-15/cmake;/usr/lib/llvm-15/lib/cmake/mlir/" -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_C_COMPILER=clang-15 -DCMAKE_CXX_COMPILER=clang++-15 ..
          scan-build -o ../pr-analysis make

      - name: Compare scan-build results
        run: |
          python3 -m pip install beautifulsoup4
          python3 scripts/compare_scan_build_reports.py base-analysis pr-analysis

